[package]
name = "autodl-rss"
version = "0.1.0"
authors = ["VanillaBrooks <brookskarlik@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rss = "1.8.0"

reqwest = "0.9.20"

serde-xml-rs = "0.3.1"
serde_yaml = "0.8.9"
serde_json = "1.0.40"
serde = {version = "1.0.101", features= ["serde_derive"]}